[project]
name = "tem"
version = "0.1.0"
dependencies = [
    "numpy",
    "scipy",
    "torch",
    "tensorflow",
    "matplotlib"
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"
